### ISSUE TITLE
Pet name 'Gryphatrice-Jubilant' not recognized

### ISSUE THREAD

**Issue by JoshMiles** [melvio/hopla#234]
Hey,
Just received this error: 

`hopla.hoplalib.zoo.petmodels.InvalidPet: pet_name='Gryphatrice-Jubilant' is not recognized by hopla.`

Presumably this is due to this pet only just being added?

**Comment by melvio** [comment]
Jup;

**Comment by melvio** [comment]
Thanks for your report @JoshMiles . The fix has been released.
